doc: add revoke.bash script to avoid requiring wsbrd_cli as DUT
The rust toolchain and dependencies create some errors on some hosts,
which makes it undesirable to use for certification to prevent any
unnecessary debugging.

Example error triggered on a Raspberry Pi image:

    $ cargo fetch --manifest-path=tools/wsbrd_cli/Cargo.toml
        Updating crates.io index
    error: Unable to update registry `crates-io`

    Caused by:
      failed to fetch `https://github.com/rust-lang/crates.io-index`

    Caused by:
      network failure seems to have happened
      if a proxy or similar is necessary `net.git-fetch-with-cli` may help here
      https://doc.rust-lang.org/cargo/reference/config.html#netgit-fetch-with-cli

    Caused by:
      SSL error: 0xffff8780 - SSL - The peer notified us that the connection is going to be closed; class=Ssl (16)