wsbrd: fix missing reallocarray() declaration
The following warning was produced on some platforms:

app_wsbrd/rcp_api.c: In function ‘rcp_rx_rf_list’:
app_wsbrd/rcp_api.c:862:38: warning: implicit declaration of function ‘reallocarray’; did you mean ‘realloc’? [-Wimplicit-function-declaration]
         ctxt->rcp.rail_config_list = reallocarray(ctxt->rcp.rail_config_list, i + 2, sizeof(struct rcp_rail_config));
                                      ^~~~~~~~~~~~
                                      realloc
app_wsbrd/rcp_api.c:862:36: warning: assignment to ‘struct rcp_rail_config *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
         ctxt->rcp.rail_config_list = reallocarray(ctxt->rcp.rail_config_list, i + 2, sizeof(struct rcp_rail_config));
                                    ^