build: fix reallocarray() warning
Building on a Raspberry Pi produces the following warning:

    app_wsbrd/rcp_api.c: In function ‘rcp_cnf_radio_list’:
    app_wsbrd/rcp_api.c:369:33: warning: implicit declaration of function ‘reallocarray’; did you mean ‘realloc’? [-Wimplicit-function-declaration]
             rcp->rail_config_list = reallocarray(rcp->rail_config_list, i + 2, sizeof(struct rcp_rail_config));
                                     ^~~~~~~~~~~~
                                     realloc
    app_wsbrd/rcp_api.c:369:31: warning: assignment to ‘struct rcp_rail_config *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
             rcp->rail_config_list = reallocarray(rcp->rail_config_list, i + 2, sizeof(struct rcp_rail_config));
                                   ^

reallocarray() is a GNU extension, and 'man reallocarray' documents:

    Feature Test Macro Requirements for glibc (see feature_test_macros(7)):

       reallocarray():
           Since glibc 2.29:
               _DEFAULT_SOURCE
           glibc 2.28 and earlier:
               _GNU_SOURCE