build: add missing inttypes.h to ws_neigh.c
This produced a compilation error when building with libsystemd
disabled:

    In file included from ../stack/source/6lowpan/ws/ws_neigh.c:27:
    ../stack/source/6lowpan/ws/ws_neigh.c: In function ‘ws_neigh_calculate_ufsi_drift’:
    ../stack/source/6lowpan/ws/ws_neigh.c:200:89: error: expected ‘)’ before ‘PRId64’
      200 |             TRACE(TR_NEIGH_15_4, "15.4 neighbor sync %s / %.01lfppm drift (%.0lfus in %"PRId64"s)", tr_eui64(address),
          |                                                                                         ^~~~~~